# CoreRAD %s configuration file

# All duration values are specified in Go time.ParseDuration format:
# https://golang.org/pkg/time/#ParseDuration.

# Interfaces which will be used to serve IPv6 NDP router advertisements.
[[interfaces]]
name = "eth0"

# AdvSendAdvertisements: indicates whether or not this interface will send
# periodic router advertisements and respond to router solicitations.
#
# Must be set to true to enable serving on this interface.
advertise = false

# All other interface parameters in this section can be removed to simplify
# configuration with sane defaults.

# MaxRtrAdvInterval: the maximum time between sending unsolicited multicast
# router advertisements. Must be between 4 and 1800 seconds.
max_interval = "600s"

# MinRtrAdvInterval: the minimum time between sending unsolicited multicast
# router advertisements. Must be between 3 and (.75 * max_interval) seconds.
# An empty string or the value "auto" will compute a sane default.
min_interval = "auto"

# AdvManagedFlag: indicates if hosts should request address configuration from a
# DHCPv6 server.
managed = false

# AdvOtherConfigFlag: indicates if additional configuration options are
# available from a DHCPv6 server.
other_config = false

# AdvReachableTime: indicates how long a node should treat a neighbor as
# reachable. 0 or empty string mean this value is unspecified by this router.
reachable_time = "0s"

# AdvRetransTimer: indicates how long a node should wait before retransmitting
# neighbor solicitations. 0 or empty string mean this value is unspecified by
# this router.
retransmit_timer = "0s"

# AdvCurHopLimit: indicates the value that should be placed in the Hop Limit
# field in the IPv6 header. Must be between 0 and 255. 0 means this value
# is unspecified by this router.
hop_limit = 64

# AdvDefaultLifetime: the value sent in the router lifetime field. Must be
# 0 or between max_interval and 9000 seconds. An empty string is treated as 0,
# or the value "auto" will compute a sane default.
default_lifetime = "auto"

# AdvLinkMTU: attaches a NDP MTU option to the router advertisement, so clients
# can set their link MTU as recommended by the router. 0 means this value is
# unspecified by this router.
mtu = 0

# AdvSourceLLAddress: attaches a NDP source link-layer address option to the
# router advertisement. Defaults to true when omitted.
source_lla = true

# Indicates whether or not CoreRAD will issue multicast router advertisements.
# In this mode, machines on this interface's LAN must issue individual router
# solicitations in order to receive router advertisements.
unicast_only = false

# Indicates the preference of this router over other default routers. Only the
# values "low", "medium", and "high" are allowed. An empty string is treated as
# "medium".
preference = "medium"

  # Prefix: attaches a NDP Prefix Information option to the router advertisement.
  [[interfaces.prefix]]
  # Serve Prefix Information options for each IPv6 prefix on this interface
  # configured with a /64 CIDR mask. Only /64 is allowed for this special case.
  prefix = "::/64"

  # Specifies on-link and autonomous address autoconfiguration (SLAAC) flags
  # for this prefix. Both default to true.
  on_link = true
  autonomous = true

  # Specifies the preferred and valid lifetimes for this prefix. The preferred
  # lifetime must not exceed the valid lifetime. By default, the preferred
  # lifetime is 4 hours and the valid lifetime is 24 hours. "auto" uses the
  # defaults. "infinite" means this prefix should be used forever.
  preferred_lifetime = "auto"
  valid_lifetime = "auto"

  # Alternatively, serve an explicit IPv6 prefix.
  [[interfaces.prefix]]
  prefix = "2001:db8::/64"

  # RDNSS: attaches a NDP Recursive DNS Servers option to the router advertisement.
  [[interfaces.rdnss]]
  # The maximum time these RDNSS addresses may be used for name resolution.
  # An empty string or 0 means these servers should no longer be used.
  # "auto" will compute a sane default. "infinite" means these servers should
  # be used forever.
  lifetime = "auto"
  servers = ["2001:db8::1", "2001:db8::2"]

  # DNSSL: attaches a NDP DNS Search List option to the router advertisement.
  [[interfaces.dnssl]]
  # The maximum time these DNSSL domain names may be used for name resolution.
  # An empty string or 0 means these search domains should no longer be used.
  # "auto" will compute a sane default. "infinite" means these search domains
  # should be used forever.
  lifetime = "auto"
  domain_names = ["foo.example.com"]

# Enable or disable the debug HTTP server for facilities such as Prometheus
# metrics and pprof support.
#
# Warning: do not expose pprof on an untrusted network!
[debug]
address = "localhost:9430"
prometheus = false
pprof = false
