# CoreRAD vALPHA configuration file

# Interfaces which will be used to serve IPv6 NDP router advertisements.
[[interfaces]]
name = "eth0"

# AdvSendAdvertisements: indicates whether or not this interface will send
# periodic router advertisements and respond to router solicitations.
send_advertisements = true

# MaxRtrAdvInterval: the maximum time between sending unsolicited multicast
# router advertisements. Must be between 4 and 1800 seconds.
max_interval = "600s"

# MinRtrAdvInterval: the minimum time between sending unsolicited multicast
# router advertisements. Must be between 3 and (.75 * max_interval) seconds.
# An empty string or the value "auto" will compute a sane default.
min_interval = "auto"

# AdvManagedFlag: indicates if hosts should request address configuration from a
# DHCPv6 server.
managed = false

# AdvOtherConfigFlag: indicates if additional configuration options are
# available from a DHCPv6 server.
other_config = false

# AdvDefaultLifetime: the value sent in the router lifetime field. Must be
# 0 or between max_interval and 9000 seconds. An empty string is treated as 0,
# or the value "auto" will compute a sane default.
default_lifetime = "auto"

  # Zero or more plugins may be specified to modify the behavior of the router
  # advertisements produced by CoreRAD.

  # "prefix" plugin: attaches a NDP Prefix Information option to the router
  # advertisement.
  [[interfaces.plugins]]
  name = "prefix"
  # Serve Prefix Information options for each IPv6 prefix on this interface
  # configured with a /64 CIDR mask.
  prefix = "::/64"
  on_link = true
  autonomous = true
  # Durations are specified in Go time.ParseDuration format:
  # https://golang.org/pkg/time/#ParseDuration.
  preferred_lifetime = "5m"
  valid_lifetime = "10m"
  # As a special case, lifetime values can be infinite by specifying "infinite".
  # valid_lifetime = "infinite"

  # Alternatively, serve an explicit IPv6 prefix.
  [[interfaces.plugins]]
  name = "prefix"
  prefix = "2001:db8::/64"
  on_link = true
  autonomous = true
  preferred_lifetime = "5m"
  valid_lifetime = "10m"

  # "rdnss" plugin: attaches a NDP Recursive DNS Servers option to the router
  # advertisement.
  [[interfaces.plugins]]
  name = "rdnss"
  lifetime = "10m"
  servers = ["2001:db8::1", "2001:db8::2"]

  # "dnssl" plugin: attaches a NDP DNS Search List option to the router
  # advertisement.
  [[interfaces.plugins]]
  name = "dnssl"
  lifetime = "10m"
  domain_names = ["foo.example.com"]

  # "mtu" plugin: attaches a NDP MTU option to the router advertisement.
  [[interfaces.plugins]]
  name = "mtu"
  mtu = 1500

# Enable or disable the debug HTTP server for facilities such as Prometheus
# metrics and pprof support.
#
# Warning: do not expose pprof on an untrusted network!
[debug]
address = "localhost:9430"
prometheus = true
pprof = false
