# CoreRAD vALPHA configuration file

# All duration values are specified in Go time.ParseDuration format:
# https://golang.org/pkg/time/#ParseDuration.

# Interfaces which will be used to serve IPv6 NDP router advertisements.
[[interfaces]]
name = "eth0"

# AdvSendAdvertisements: indicates whether or not this interface will send
# periodic router advertisements and respond to router solicitations.
send_advertisements = true

# MaxRtrAdvInterval: the maximum time between sending unsolicited multicast
# router advertisements. Must be between 4 and 1800 seconds.
max_interval = "600s"

# MinRtrAdvInterval: the minimum time between sending unsolicited multicast
# router advertisements. Must be between 3 and (.75 * max_interval) seconds.
# An empty string or the value "auto" will compute a sane default.
min_interval = "auto"

# AdvManagedFlag: indicates if hosts should request address configuration from a
# DHCPv6 server.
managed = false

# AdvOtherConfigFlag: indicates if additional configuration options are
# available from a DHCPv6 server.
other_config = false

# AdvReachableTime: indicates how long a node should treat a neighbor as
# reachable. 0 or empty string mean this value is unspecified by this router.
reachable_time = "0s"

# AdvRetransTimer: indicates how long a node should wait before retransmitting
# neighbor solicitations. 0 or empty string mean this value is unspecified by
# this router.
retransmit_timer = "0s"

# AdvCurHopLimit: indicates the value that should be placed in the Hop Limit
# field in the IPv6 header. Must be between 0 and 255. 0 means this value
# is unspecified by this router.
hop_limit = 64

# AdvDefaultLifetime: the value sent in the router lifetime field. Must be
# 0 or between max_interval and 9000 seconds. An empty string is treated as 0,
# or the value "auto" will compute a sane default.
default_lifetime = "auto"

  # Zero or more plugins may be specified to modify the behavior of the router
  # advertisements produced by CoreRAD.

  # "prefix" plugin: attaches a NDP Prefix Information option to the router
  # advertisement.
  [[interfaces.plugins]]
  name = "prefix"
  # Serve Prefix Information options for each IPv6 prefix on this interface
  # configured with a /64 CIDR mask.
  prefix = "::/64"
  # Specifies on-link and autonomous address autoconfiguration (SLAAC) flags
  # for this prefix. Both default to true.
  on_link = true
  autonomous = true
  # Specifies the preferred and valid lifetimes for this prefix. The preferred
  # lifetime must not exceed the valid lifetime. By default, the preferred
  # lifetime is 7 days and the valid lifetime is 30 days. "auto" uses the
  # defaults. "infinite" means this prefix should be used forever.
  preferred_lifetime = "5m"
  valid_lifetime = "10m"

  # Alternatively, serve an explicit IPv6 prefix.
  [[interfaces.plugins]]
  name = "prefix"
  prefix = "2001:db8::/64"

  # "rdnss" plugin: attaches a NDP Recursive DNS Servers option to the router
  # advertisement.
  [[interfaces.plugins]]
  name = "rdnss"
  # The maximum time these RDNSS addresses may be used for name resolution.
  # An empty string or 0 means these servers should no longer be used.
  # "auto" will compute a sane default. "infinite" means these servers should
  # be used forever.
  lifetime = "auto"
  servers = ["2001:db8::1", "2001:db8::2"]

  # "dnssl" plugin: attaches a NDP DNS Search List option to the router
  # advertisement.
  [[interfaces.plugins]]
  name = "dnssl"
  # The maximum time these DNSSL domain names may be used for name resolution.
  # An empty string or 0 means these search domains should no longer be used.
  # "auto" will compute a sane default. "infinite" means these search domains
  # should be used forever.
  lifetime = "auto"
  domain_names = ["foo.example.com"]

  # "mtu" plugin: attaches a NDP MTU option to the router advertisement.
  [[interfaces.plugins]]
  name = "mtu"
  mtu = 1500

# Enable or disable the debug HTTP server for facilities such as Prometheus
# metrics and pprof support.
#
# Warning: do not expose pprof on an untrusted network!
[debug]
address = "localhost:9430"
prometheus = true
pprof = false
