baseURL = "https://corerad.net/"
languageCode = "en-us"
title = "CoreRAD"
theme = "anubis"
enableRobotsTXT = true

[menu]
  [[menu.main]]
    name = "GitHub"
    title = "Source code on GitHub"
    url = "https://github.com/mdlayher/corerad"
    weight = 60

[params]
  Description = "CoreRAD - extensible and observable IPv6 NDP router advertisement daemon"
  Source = "github.com/mdlayher/corerad"
  css = ["/css/style.css", "/css/override.css"]
